package com.inventory.manager.exception;

public enum CustomExceptionCodes {

    DUPLICATE_SUPPLIER_NAME,
    SUPPLIER_NOT_FOUND,
    
    DUPLICATE_CUSTOMER_NAME,
    CUSTOMER_NOT_FOUND,
    
    DUPLICATE_ITEM_CODE,
    DUPLICATE_ITEM_NAME,
    
    DUPLICATE_LOCATION,
    INVALID_QUANTITY,
    
    ITEM_NOT_FOUND,
    ITEM_NAME_REQUIRED,
    ITEM_CODE_REQUIRED,
    ITEM_CANNOT_BE_DELETED,
    ITEM_ALREADY_DELETED,
    
    GRN_NOT_FOUND,
    SALES_INVOICE_NOT_FOUND,
    TRANSFER_NOTE_NOT_FOUND,
    
    INSUFFICIENT_QUANTITY,
    
    PRICE_REQUIRED,
    INVALID_PRICE,
    
    DISCOUNT_MODE_REQUIRED,
    DISCOUNT_VALUE_REQUIRED,
    INVALID_DISCOUNT_VALUE,
    INVALID_DISCOUNT_MODE;
}
